import { ArrowRight, Globe2, Leaf, Target, Users, Handshake, Sprout, MapPin } from 'lucide-react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { AnimatedPageHero } from '../../components/ui/AnimatedPageHero'
import { companyContent } from '../../data/companyContent'
import './About.css'

const values=[['Export mindset','Building business conversations around international opportunities.',Globe2],['Requirement focused','Understanding the buyer requirement before moving forward.',Target],['Long-term partnerships','Creating dependable relationships through direct communication.',Handshake],['Responsible growth','Growing product opportunities with a practical business direction.',Sprout]]

export function About(){const {overview,businessPrinciples}=companyContent;return <><section className="page-hero page-hero--about"><AnimatedPageHero label="ABOUT STOCON BHARATH" prefix="From India, with an" typed="export-first direction." description="STOCON BHARATH PRIVATE LIMITED is based in India and focused primarily on export business."/></section>
<section className="about-story"><motion.div className="about-story__copy" initial={{opacity:0,x:-24}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><span className="section-label">WHO WE ARE</span><h2>A new company with a clear <em>business direction.</em></h2><p>{overview.primaryFocus}</p><p>{overview.domesticSales}</p><p>Our approach is straightforward: understand the product requirement, discuss the opportunity clearly and build the right path for the customer and market.</p><Link to="/products">Explore our product categories <ArrowRight size={17}/></Link></motion.div>
<div className="about-story__cards">{[[Target,'Established','STOCON BHARATH PRIVATE LIMITED was established in August 2025.'],[Leaf,'Current focus','Food products, fruits, vegetables and spices form the current business direction.'],[Globe2,'Future direction',overview.futureDirection]].map(([Icon,title,text],i)=>{const I=Icon as typeof Target;return <motion.article key={String(title)} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} whileHover={{y:-7}} transition={{delay:i*.08}}><I/><h3>{String(title)}</h3><p>{String(text)}</p></motion.article>})}</div></section>
<section className="about-direction"><div><span className="section-label">HOW WE THINK</span><h2>Focused on products. Connected to <em>markets and people.</em></h2><p>Every business opportunity begins with a requirement. STOCON aims to keep discussions practical, transparent and focused on the product, market and customer need.</p></div><div className="about-values">{values.map(([title,text,Icon],i)=>{const I=Icon as typeof Globe2;return <motion.article key={String(title)} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}}><I/><h3>{String(title)}</h3><p>{String(text)}</p></motion.article>})}</div></section>
<section className="about-principles"><div><span className="section-label">BUSINESS PRINCIPLES</span><h2>A practical direction, <em>built around requirements.</em></h2><p>We believe clear communication and a defined requirement create a stronger starting point for every business discussion.</p></div><div className="about-principles__list">{businessPrinciples.map(({title,text},index)=><motion.article key={title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}}><span>0{index+1}</span><div><h3>{title}</h3><p>{text}</p></div></motion.article>)}</div></section>
<section className="about-closing"><MapPin/><div><span className="section-label">LET'S CONNECT</span><h2>From India to the <em>next opportunity.</em></h2><p>Whether you have a product requirement or want to begin an export-focused discussion, STOCON is ready to hear from you.</p></div><Link to="/contact">Contact STOCON <ArrowRight size={18}/></Link></section></>}