import { ArrowRight, Boxes, ClipboardCheck, FileCheck2, Globe2, Handshake, Plane, Ship, Snowflake, Truck, Warehouse } from 'lucide-react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { AnimatedPageHero } from '../../components/ui/AnimatedPageHero'
import { companyContent } from '../../data/companyContent'
import './Services.css'

const serviceGroups=[
 {label:'EXPORT LOGISTICS',title:'Move products with a coordinated logistics plan.',text:'Coordinate the practical movement of fresh and food products from preparation through dispatch and destination delivery.',items:[['Air freight','Suitable for time-sensitive or smaller consignments.',Plane],['Sea freight','Suitable for larger shipments and containerized export movement.',Ship],['Transportation','Coordinate inland movement between sourcing, packing, storage and dispatch.',Truck],['Cold-chain handling','Temperature-controlled handling where product requirements call for it.',Snowflake]]},
 {label:'PRODUCT & QUALITY',title:'Prepare the right product for the right market.',text:'Product selection and preparation can be aligned with buyer specifications, quality expectations and destination requirements.',items:[['Product sourcing','Requirement-based sourcing through Indian suppliers and agricultural networks.',Globe2],['Variety identification','Match product varieties and specifications to buyer requirements.',Boxes],['Grading & inspection','Review size, appearance, freshness and agreed quality parameters.',ClipboardCheck],['Export packaging','Select practical packaging formats for product protection and transit.',Warehouse]]},
 {label:'TRADE SUPPORT',title:'Keep documentation and communication clear.',text:'A smoother export journey depends on accurate information, coordinated paperwork and consistent communication between the parties.',items:[['Documentation support','Coordinate commercial and shipment documentation required for the agreed trade flow.',FileCheck2],['Customs coordination','Support the information flow around customs and export clearance.',ClipboardCheck],['Supply discussions','Discuss recurring quantities, specifications and commercial requirements.',Handshake],['Global buyer coordination','Keep product, shipment and destination discussions connected from enquiry to dispatch.',Globe2]]}
]

export function Services(){return <><section className="page-hero page-hero--services"><AnimatedPageHero label="OUR SERVICES" prefix="From product sourcing to" typed="global shipment." description="STOCON BHARATH supports requirement-based sourcing, quality preparation, export packaging, documentation and logistics coordination."/></section>
<section className="services-intro"><div><span className="section-label">END-TO-END SUPPORT</span><h2>One coordinated process from <em>source to destination.</em></h2></div><p>Our service approach is built around the practical stages of an export order. The exact process, packaging, shipment mode and documentation depend on the product, quantity, destination and buyer requirements.</p></section>
{serviceGroups.map((group,gi)=><section className={'service-group '+(gi%2?'service-group--tint':'')} key={group.label}><div className="service-group__head"><span className="section-label">{group.label}</span><h2>{group.title}</h2><p>{group.text}</p></div><div className="service-group__grid">{group.items.map(([title,text,Icon],i)=>{const I=Icon as typeof Boxes;return <motion.article key={String(title)} initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}}><span className="service-number">0{i+1}</span><I/><h3>{String(title)}</h3><p>{String(text)}</p></motion.article>})}</div></section>)}
<section className="services-cta"><div><span className="section-label">START A REQUIREMENT</span><h2>Tell us the product, quantity and <em>destination market.</em></h2><p>{companyContent.overview.primaryFocus}</p></div><Link to="/contact">Request an enquiry <ArrowRight size={18}/></Link></section></>}