import { PackageSearch, Tag, ClipboardCheck, Box, Globe2, Truck } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { AnimatedPageHero } from '../../components/ui/AnimatedPageHero'
import { ProductCatalogModal } from '../../components/catalog/ProductCatalogModal'
import { productCategories } from '../../data/products'
import type { ProductCategory } from '../../types/product'
import './Categories.css'

const productNotes=[['Specification','Share grade, size, variety, freshness or other product specifications that matter to your market.',ClipboardCheck],['Packaging','Tell us the preferred packing format, unit size or labelling requirement where applicable.',Box],['Destination','Destination country or city helps us understand the intended logistics and shipment route.',Globe2],['Quantity','Share your approximate quantity or recurring requirement so the supply discussion can be more precise.',Truck]]

export function Categories(){const [selectedCategory,setSelectedCategory]=useState<ProductCategory|null>(null);return <><section className="page-hero page-hero--products"><AnimatedPageHero label="OUR PRODUCTS" prefix="Explore India's finest products by" typed="category." description="Choose a category and open its product catalogue instantly without leaving the page."/></section><section className="categories-page"><div className="categories-page__intro"><div><span className="section-label">OUR PRODUCTS</span><h2>Explore what India <em>grows and creates.</em></h2></div><div className="categories-page__note"><PackageSearch size={25}/><p>Our catalogue covers fresh produce, food products, spices and imported fruits. Product availability can vary by season, market and buyer requirement.</p></div></div><div className="categories-page__grid">{productCategories.map((category,index)=><motion.button type="button" key={category.id} className="categories-page__card" initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}} whileHover={{y:-6}} onClick={()=>setSelectedCategory(category)}><img src={category.image} alt={category.title}/><div className="categories-page__shade"/><div className="categories-page__meta"><span className="categories-page__number">0{index+1}</span><span className="categories-page__tag"><Tag size={12}/> PRODUCT CATEGORY</span></div><div className="categories-page__copy"><h3>{category.title}</h3><p>{category.description}</p><span className="categories-page__action">View product catalogue</span></div></motion.button>)}</div></section>

<section className="products-buying"><div className="products-buying__intro"><span className="section-label">PLAN YOUR REQUIREMENT</span><h2>Give us the details that make a <em>trade conversation useful.</em></h2><p>Product enquiries become easier to coordinate when the key specifications are shared upfront.</p></div><div className="products-buying__grid">{productNotes.map(([title,text,Icon],index)=>{const I=Icon as typeof ClipboardCheck;return <motion.article key={String(title)} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}}><I/><span>0{index+1}</span><h3>{String(title)}</h3><p>{String(text)}</p></motion.article>})}</div><Link className="products-buying__cta" to="/contact">Send a product enquiry <Truck size={17}/></Link></section>
<ProductCatalogModal category={selectedCategory} onClose={()=>setSelectedCategory(null)}/></>}