import { PackageSearch, Tag } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { AnimatedPageHero } from '../../components/ui/AnimatedPageHero'
import { ProductCatalogModal } from '../../components/catalog/ProductCatalogModal'
import { productCategories } from '../../data/products'
import type { ProductCategory } from '../../types/product'
import './Categories.css'

export function Categories(){const [selectedCategory,setSelectedCategory]=useState<ProductCategory|null>(null);return <><section className="page-hero page-hero--products"><AnimatedPageHero label="OUR PRODUCTS" prefix="Explore India's finest products by" typed="category." description="Choose a category and open its product catalogue instantly without leaving the page."/></section><section className="categories-page"><div className="categories-page__intro"><div><span className="section-label">OUR PRODUCTS</span><h2>Explore what India <em>grows and creates.</em></h2></div><div className="categories-page__note"><PackageSearch size={25}/><p>Tap any product category to open the complete catalogue and send your requirement directly on WhatsApp.</p></div></div><div className="categories-page__grid">{productCategories.map((category,index)=><motion.button type="button" key={category.id} className="categories-page__card" initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}} whileHover={{y:-6}} onClick={()=>setSelectedCategory(category)}><img src={category.image} alt={category.title}/><div className="categories-page__shade"/><div className="categories-page__meta"><span className="categories-page__number">0{index+1}</span><span className="categories-page__tag"><Tag size={12}/> PRODUCT CATEGORY</span></div><div className="categories-page__copy"><h3>{category.title}</h3><p>{category.description}</p><span className="categories-page__action">View product catalogue</span></div></motion.button>)}</div></section><ProductCatalogModal category={selectedCategory} onClose={()=>setSelectedCategory(null)}/></>}