import { PackageSearch, Tag, ClipboardCheck, Box, Globe2, Truck, ChevronDown, ShieldCheck, Clock3, Leaf, FileCheck2 } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { AnimatedPageHero } from '../../components/ui/AnimatedPageHero'
import { ProductCatalogModal } from '../../components/catalog/ProductCatalogModal'
import { productCategories } from '../../data/products'
import type { ProductCategory } from '../../types/product'
import './Categories.css'

const productNotes=[['Specification','Share grade, size, variety, freshness or other product specifications that matter to your market.',ClipboardCheck],['Packaging','Tell us the preferred packing format, unit size or labelling requirement where applicable.',Box],['Destination','Destination country or city helps us understand the intended logistics and shipment route.',Globe2],['Quantity','Share your approximate quantity or recurring requirement so the supply discussion can be more precise.',Truck]]
const buyerReasons=[['Quality-focused sourcing','Product discussions can include sorting, grading, inspection and agreed specifications.',ShieldCheck],['Freshness & handling','Fresh products can be planned around appropriate storage, packing and temperature-controlled handling.',Leaf],['Shipment coordination','Air or sea freight, transportation and dispatch can be coordinated around the agreed order.',Clock3],['Documentation support','Commercial and export documentation requirements can be discussed as part of the shipment flow.',FileCheck2]]
const faqs=[['What products can I source from STOCON?','Our current catalogue covers fresh vegetables, fresh fruits, food and non-perishable products, imported fruits, spices and grains or pulses. Availability depends on product, season and buyer requirement.'],['Do you handle bulk requirements?','Yes. Share the product, approximate quantity, destination and preferred specifications so the requirement can be discussed at the appropriate scale.'],['Can packaging be customized?','Packaging can be discussed according to product characteristics, destination requirements, shipment mode and buyer specifications.'],['Do you support export documentation and logistics?','We can coordinate documentation, transportation and air or sea freight requirements as part of the agreed export process.'],['How do I request availability and pricing?','Open the enquiry form, select your category and products, then include quantity, destination and any quality or packaging requirements.']]

export function Categories(){const [selectedCategory,setSelectedCategory]=useState<ProductCategory|null>(null);const [openFaq,setOpenFaq]=useState<number|null>(null);return <><section className="page-hero page-hero--products"><AnimatedPageHero label="OUR PRODUCTS" prefix="Explore India's finest products by" typed="category." description="Choose a category and open its product catalogue instantly without leaving the page."/></section><section className="categories-page"><div className="categories-page__intro"><div><span className="section-label">OUR PRODUCTS</span><h2>Explore what India <em>grows and creates.</em></h2></div><div className="categories-page__note"><PackageSearch size={25}/><p>Our catalogue covers fresh produce, food products, spices and imported fruits. Product availability can vary by season, market and buyer requirement.</p></div></div><div className="categories-page__grid">{productCategories.map((category,index)=><motion.button type="button" key={category.id} className="categories-page__card" initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}} whileHover={{y:-6}} onClick={()=>setSelectedCategory(category)}><img src={category.image} alt={category.title}/><div className="categories-page__shade"/><div className="categories-page__meta"><span className="categories-page__number">0{index+1}</span><span className="categories-page__tag"><Tag size={12}/> PRODUCT CATEGORY</span></div><div className="categories-page__copy"><h3>{category.title}</h3><p>{category.description}</p><span className="categories-page__action">View product catalogue</span></div></motion.button>)}</div></section>
<section className="products-reasons"><div className="products-reasons__intro"><span className="section-label">WHY BUYERS WORK WITH US</span><h2>Product supply with the <em>details connected.</em></h2><p>From sourcing and quality checks to packaging and shipment coordination, the objective is to keep the important parts of the order aligned.</p></div><div className="products-reasons__grid">{buyerReasons.map(([title,text,Icon],index)=>{const I=Icon as typeof ShieldCheck;return <motion.article key={String(title)} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><span>0{index+1}</span><I/><h3>{String(title)}</h3><p>{String(text)}</p></motion.article>})}</div></section>
<section className="products-buying"><div className="products-buying__intro"><span className="section-label">PLAN YOUR REQUIREMENT</span><h2>Give us the details that make a <em>trade conversation useful.</em></h2><p>Product enquiries become easier to coordinate when the key specifications are shared upfront.</p></div><div className="products-buying__grid">{productNotes.map(([title,text,Icon],index)=>{const I=Icon as typeof ClipboardCheck;return <motion.article key={String(title)} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.06}}><I/><span>0{index+1}</span><h3>{String(title)}</h3><p>{String(text)}</p></motion.article>})}</div><Link className="products-buying__cta" to="/contact">Send a product enquiry <Truck size={17}/></Link></section>
<section className="products-faq"><div className="products-faq__heading"><span className="section-label">PRODUCT FAQ</span><h2>Common questions before <em>you enquire.</em></h2></div><div className="products-faq__list">{faqs.map(([question,answer],index)=><button type="button" key={question} className={'products-faq__item '+(openFaq===index?'is-open':'')} onClick={()=>setOpenFaq(openFaq===index?null:index)}><div><strong>{question}</strong>{openFaq===index&&<p>{answer}</p>}</div><ChevronDown size={19}/></button>)}</div></section>
<ProductCatalogModal category={selectedCategory} onClose={()=>setSelectedCategory(null)}/></>}